### ISSUE TITLE
polls/14_FirstStep.csv

### ISSUE THREAD

**Issue by thomasmanke** [maxplanck-ie/Rseurat#90]
line 2: correct answer is missing: 32738 genes / 2700 cells (I would add 2700 genes / 32738 cells, and perhaps 13714/ 2700 to identify the impatient
line 3:  16104 (correct), 16634, 0, 32738
line 8:  order of VariableFeatures() unclear, perhaps the better hint would be HVFInfo()?
line 10: challenging - perhaps skip. I would also replace "divergent between themselves" with "distant from another".
line 11: I would offer "2" as one answer, because many people think that PCA projections only have PC1 and PC2

**Comment by adRn-s** [comment]
line 2 & 3: corrected, thanks!

line 8: just confirmed that `HVFInfo(pbmc) %>% arrange(-variance.standardized) %>%  head(3)` is the same as `VariableFeatures() %>% head(3) `.  It's true, using the second one looks trivial, we may skip this question. But I'm also inclined on keeping it, because they can play around with the simplest solution and the simplest question first, then move onto the next question that hints them onto using HVFInfo... so the 'build-up' scheme may be a pedagogical advantage..

line 10: I will add a plot, this was on my todo list. I value the question because it should be clear the hierarchy of PCs... of course, the correct answer is actually wrong in the case of a dataset that had equal amounts of variance on the first two PCs... one should look into the scree plot.... that's to be discussed, or not, maybe depending on if it comes up.

line 11: good one... or shall I say evil one? ;)
